server:
  port: 8092
spring:
  cloud:
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: index-route
          uri: lb://index-service
          predicates:
            - Path=/api/index/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
            - Auth             #使用的是AuthGatewayFilter访问index时进行拦截token验证
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#网关获取到token之后请求订单等微服务
gmall:
  jwt:
    pubKeyPath: D:\\Program Files\\ideaworkspaces\\glshop\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN