server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: 192.168.160.133:9200
  jackson:
    default-property-inclusion: non_null #如果json反序列化数据为null时不会反序列化