server:
  port: 8086
spring:
  application:
    name: search-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: 192.168.160.133:9200
  rabbitmq:
    password: xiaoxiong
    username: xiaoxiong
    host: 127.0.0.1
    port: 5672
    virtual-host: /xiaoxiong
