spring:
  application:
    name: cart-service
  redis:
    url: 192.168.160.133
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /xiaoxiong
    username: xiaoxiong
    password: xiaoxiong
server:
  port: 8092
#网关获取到token之后请求订单等微服务
gmall:
  jwt:
    pubKeyPath: D:\\Program Files\\ideaworkspaces\\glshop\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
    userKey: user-key
alipay:
  app_id: 2021000117608622 #在阿里支付开放平台控制台使用沙箱应用Appid
  #私钥通过alipay工具生成RSA2
  merchant_private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCv60x6d8c87FknGIYMxQflsxHJMRJg00QWc8oUznbRaz7Ey8TjDIYLayAQDKajUV81lGEmGBruFQcZqXw4fslo7kELhZR3dmzItP+c16z1L28c7UHoSEhfglEqAGTEyzGVvtEOGAUpoFe5Bi55bHn9glVVy0V8bFLqDyq/D4KBL9x12ARvLeCJvNqEhgI8sz8hBW5Ibl5lHfVCLVkNWEwQmhF7W5jl+GMf4RXHN+I0U+yMEA2LUQT0yUfa0noeJMryH5w6uQbg8q/7rBrgrlUhtBPDpcAIdGd82ZUDYHeF+fBtJTUJ6gjnHK10P+VrhZ3s63yZNHW7w5LQYHF/y0OJAgMBAAECggEBAJzj7MEMMdRTtO75IBQjZHemzCXybcGMqRydB4ym1bDPRJueX2lese1dDKtDnRnqaE8QldOzi9DpT/vC+9YmvNmoIrpz14TzSPF2+sCWWNoSA7Z4ol7WmDUVs+0RjM01qnMySp+XLIODTLjmmmwQInvE0PZC4yWkNg4omKbs3ib3WzwyC3IAjTEbU9p9q1CPRXZpMrnWrI3wivUCBJH2Xmzfo9SXmMyXyJ083RdEUEcJ+QCQEM/u511MRBbM2hUT0ksm6ajscWGZZRzIsMS5NaFanFk1f7BYqgDu15iRnt9GJYVJuj+6iqo5eXBoXQx/WB5xnUCNper6/juypNhZZQECgYEA7nYAu59eRjOlv0Q75H97VEJ3fn43DWyofZemG2Xop+Gva1yKk7dBrNUSv3EI26KLViwzVa39WvTQMQD99LAqQwSKoWVWtl/xBUqD9nBWhq6Rltb2Gdb7e4C4Zl0sF2oDUY4EBOQ40UitVz6z6/8psC12j+awGlQk1d/27GRg6H0CgYEAvNuxILVolvcYao42DEwQXcZQFi4brVChpgjMXgNnBRa/aCbTWCNbueoSjKFNeiaWVx3gtOvVoR3PmJ/e0arjBaesJ69f0QnBGCEDXIOARFjamLq2IKqaX9qpusaKeGxAmnoCJRp1ZN6KF03/IDnZAAxcfFm/r5o2oTp7dTiTgP0CgYB+uHC9Q/yqW8np8Y3OaLyWU1gC/XmuBZ8oVs1r4+UWSgWZjS0LQKiC+xwiZiQp66AWJBkHoBVyH4T/daJ/RJrA0IoHKL5C3otLn4SvEpW4rs4plYRkyO0NfaMAquTCcJDg5xJVsx5KgU+0fFrKv+dce1x1LkdJRovoqEMk7lbdVQKBgQCPdD0ugD2q9pR4U/+gBaMk5/9raaiiVK4FBYffHayCRA4uWdeNioYhSTi/08KbN3ZZRBussbr7AD7xSvagwrJhWES/fEpG6abf4ivAeS7UO74H50NyusQ6bUkh06/Y2zmTXXwFnPxxG00/eIKDgw1fKQSTfETLaVN30ol2t/vrLQKBgQDBYxoWl3rIAa3SVpssVXoscOuKrCfwwAGX4+rCzVF1xMMSFdD846QpVO5F2bKE/8FbGB3wlGavJDmxDaVzWHXogSBIGOAW3A4sO0SXXSPh7fW8qDStB8QpbZJc9tY731hn8DPJzbxSgZzDesdjQa9K411AAzk0n8Lg99o77lp+fg==
  #alipay工具生成应用公钥给alipay开放平台中设置公钥，然后会生成配置的公钥
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4EUi6toqXBnzK3+/+X6Fsu840U7X4Vbb3bUAhX+UrD/8//YXK9C3B/ckZ7B7lfJjc85jaBhTFmDRc5MZNrgY0i0nx0BftJ+zZ7y1QqOe8GCO38epIB5ediIVSReV/VQtKWTgaplQkXkDAZFy5IpWIgIc9x8OadjWhloa7jjxmjE4xnh70HDpEOSevIBGYR3eXfH0UC5nh3QXNBIi9KPf9+MO2BduEt8C0o0zbbcFGU+FwKxUWzKBkHtwSNutBiNBWLLoh9FDDCtEhOlO+NaqISrnMLeaQ15piJwtpN3mrov/Lm+c9fBwnXOTcIcSmKhoPcpDMVsLhgZSPx25PAiRQwIDAQAB
  notify_url:  #内网穿透后的路径
  return_url:
  sign_type: RSA2
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
